language: java

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.m2/repository/

stages:
  - name: build
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: build
      jdk: oraclejdk8
      install:
        - ./gradlew -v
      script:
        - ./gradlew clean build
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: build
      jdk: oraclejdk9
      install:
        - ./gradlew -v
      script:
        - ./gradlew clean build

    - stage: build
      jdk: oraclejdk10
      install:
        - ./gradlew -v
      script:
        - ./gradlew clean build

    - stage: deploy
      jdk: oraclejdk8
      install:
        - ./gradlew -v
      script:
        - ./gradlew clean build -x test -x check
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_446ef87682bf_key -iv $encrypted_446ef87682bf_iv -in private-key.gpg.enc -out $SIGNING_FILE -d
      deploy:
        provider: script
        script: ./gradlew dokka publish
            -Psigning.keyId="$SIGNING_KEYID"
            -Psigning.password="$SIGNING_PASSWORD"
            -Psigning.secretKeyRingFile="$TRAVIS_BUILD_DIR/$SIGNING_FILE"
            -PossrhUsername="$OSSRH_USERNAME"
            -PossrhPassword="$OSSRH_PASSWORD"
        on:
          tags: true
      env:
        global:
          - secure: xuyde7Sn6xtyS0UbdWBHzd6gM4SaXLWmZSlUooY0Z4A15QYRWwrXLmmrLTiArvvoAt+Y+UJdSaFtLklNsW0ho2XKra/FabZJ01nBN9WmTQIgXkFHWud1HcQU0qVoHvGauB87k5HcFJQBmNLCTXux5ls5IEj8KWORfFNItw2edyhocPM0RnsBMf2sKMGFbysLTsc5W9+mdeu1dJxC+8myd7KeRv4vQIg3vkOkNPBL2B5cpq5oH0ALrlR2o9SStwmdNRP907V3QnaX2pCA7ZJLwlAAVB8NIB0AR33efUWYHyZwZ9EKrctbD1r/Zh+bKrfhsZ8CCVHQAluTlEM/aTnJlTJAEjsYnfg8jukdjeSjZsVUgA2/qey5TRRr+1rO7vp8+BYUbdaJuFVaIAjNZi24BrnOjXLyf6VzzEO2wXsPEB7mfPR56GKmpZRvMkr+5gNBSFl5fBJKIEunaZts8c1gAp2NCwQa4LwV0yhR1hwo+ONyRBle8iR5fnjF+vo5jtPGlJhYOh4f2roRL6sPb8ETezAOPNzdYpW0QJsSmiWqkRE1e10cq0/eRu2ru/O4LNZOmwMaOc/a4/Cyq5s/5V3bGxnpL9ADLFLku81B49tpBvKAzcMoDmVOzcoV4Ei/d1NbjiwRphdDcyGEjc6xNcMTpJsDNQ04Ksl8e8OCw/Kb84g=
          - secure: UpBGjhWTVD8HamgjOuACjwQY8tnNEjL47YdRw2t07lm/G7wc0jlnQaOJdw3oGZcEMYnQD6mjuy++JHBNNvXJL50CcpXr3KIOmPlxkCDTWlmmMjECfBGqQs17odj6ed8Kp7IFst+4ay/yb2UydlAcFvJgZGXD2m1cCbfLO6zs9rtBVX1aRyPl+peifGP9V2jSl57SIC5BVvOCdInm0IixkKQl8Ot6TXpPrKK2iVvOoqlfESvUIpEFGkB+2mVTW5W49YhlVNXzHUEX2Gy2H3vuBOapR9bZxq15GyCI1NbGF/GvXV/4J7/LyfxhmGoK03NuPIbgGPrxOmjxRdpJNCkBKHGDcbAl0JsMurpM3AF8OmSuBR40Vl4RXMXMUHpNnZ2ZVVVPzWzG5XlkQvD6jlYbo2r15RjVGCzb+EsfsfjpPM6E86XPfoIXYL0hk26024Pm7wPGKQmENuhAEjNqSJiV09K3OfP5NBPmGVwF9UfyfWacA/Sk56ocXQrqLjDIBIKEW15B26z5H1UZPKDmCfyeDiMGFwZ/EpWxVTETHz/kloNZB4lkBSCrJqhKTZPlCuD+KvGthbF/prvwtpwa4lbpRKJoXG6Cygg1lyrLHOL/EtTgBGDqNnpkNcnCE0XIT7eQ/fMZ+z3MS4lypznFQiCjqGzEWzO7xgF9gB4gt98gOgI=
          - secure: o/h7iFvpcjypnWfb2zR/k/jeyOEGmb4rp7C+MkjUhhJGVB6Jpu5TfX8bvinIISEsyO45qz9I+Rl0XODsq5031r7K2XiCuVT+pkDwKolWfCx/pTTUBmUVO99R4h7vU2JdncOm68NCcm8aWondiEcwQlLAL6Cl0Sz8eCxJ4wFJKEeNr9DmKAxe8MYpxsnuSD3Gj+R+MVmRx0ubqaWzHxNGZve1JGGZsDq1zkswdJs5kNJx4GSsVHJyGIu25U/oXgwKUgxdbpBSc2Ulkg6j+Y4NSp0JHaXvt5Qns9dtBbGamwLQLBYaF4G9GP3xITjUFkpSnuHPUCRP3XuYKGmF4VSFXDokiUh7rqaVrsX54g9wCXCJVPlKEawoYITEbY8U1J/hmRoZWGUo1ER8HTbXujGfg6adp3jhSAzM3ME1WKvgtbxeFWiuIPMablYCDmTJHEmj5cytwpgOh1B2LGx1tGk5qPTTIMM9XyVpUA7s2eFrtqazoeSz5AI0TW+W7ZT0Q+KWx7E/bJi1JzgKLQNfSjMboC3TID+75lc9cVqwdPrwEisBZGjrGGhk2MfHzH+BCtmdEySZ1Pas7XgukHOMRQ4ZDHgNN++I9RPKRwSZ9mp7T5sgrjmLh4mrs5Gw6DhzKGLi7M613lP+OBKVA1PWBPnMK5Qd62Mp655Mglt5aWAzSEQ=
          - secure: Gza7Ida8/vAd9aHchbP3b0c6LK2Bg43zBlbUuYWrPVAgxDbMyLyRsjxGI3toWEGv/h3s2U61iehqoHIEeJZRYt0th4YTVg8bhT/9/MNaQv6LW3uH1d+M7DcRP5CRfiWAzAtxq3mHaTACrEeODkxpLWW8H8l2fbPBXCpzUaYElzb/UbFZmkTkLX14roXeTgQI2B6iYSt0p/LMfV8yGMvDDTEmSY+JO1jAWJla3DGwqwPPXiTUY8X4+Dy1yNGf+NwsNDNibr18KNFTEH26DLAgOxCQiQruAXVgxoFv2vD9NrKWuF9lNYpkzOWYPtnQzbcVWx+uuPKt0J7NuFbq/LcQOfPygxrFFdqm23+k3pcSrivUN+FBlD4mbpDVb6avntUZYXIDAlAVN18vR4g9rynqRZqwQUXS4s1Ai3X6dggT32PqDHq2kdBj0/tyZmNh5MNxNAfCmNvvNFDNyf0L7IUjZRn2GEdQomnx2/DRPf/5WJnN7942V2ni69yf9CqaqhiEqrrwIrXy/PxdfGp6XH0Qa309jIkXkTyb370Bmf7KmI94NDSc6Yt76Z0hRvAzJxFIwyF85LLx8zKWybTIdObEscaPtyaZDUpIVvrsSs1SE22HUwTOqvivaojK4GyqHhYK9zwyhf1KLWyGnDjnQ9tCJpRODVab9F/iLWLwDD9DSY0=
          - secure: 7evSCxqqYgsyMu3pbaWv6nRzeyxU8+eygLnfmY5MoFpQz8thtvJQixWZV0VZHj7em+KFg5mRugwXRJsP3vhlbjXq2HExwP/4/I7D4E3vcEeV7REsAkitMJHKU78Z/E3Tj06cQ+NjLUFLPIhjj+UtyTeOqw1rbI/g+VS3NdSmJyohAgtO8bMsoiyoTAcGwVswdHNOIU8dYsUtCeLTcsLcii8ubcI0XAzHMDwn57iqMKzHQ56sz86eMAtnUQ3P35jGMpPNMG+BUZXE4ojjEZLT1Lm72RV+O4b2tm7YjUdrwVxUMke19cx/VkLhMaxlz8XoWLN9dvN1j9SBgwW+F9lAdxER2xgpnT504Xe9HKNH0l6SuTZ8wRxCo/zBMd9osPhMrm9J9hUu7rgBtENaNz7xP+bP6tQDmSgczAmHmUrt0qA3XeldUCfwINm9ISXevAPA17DYZDy4uDncq/neeq8IHvqqQVpBZ0JTDbCcgWCjaL1iEksdO7mqrEI7ROMPJxXpz3Jsxfub/unTBIn2Bht3MNlGnNyHINwSLpOgSF/TYUamYtNhylj/pbnzlrHkc5g7Q/6hkb4rJtoGNgA52p8nePwrZ5j5DliOlm+OrgG0I3UEak+cuJP24X/fUmFXwhU0xTJUM5HG8nmkO3uGt4yWV+hxXhFOuE4kENBebscyfjE=